### ISSUE TITLE
[BUG] 404 For All Books When Downloading Files On Latest Image

### ISSUE THREAD

**Issue by Chirishman** [linuxserver/docker-cops#44] opened 2023-08-13 03:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to download a book via web or OPDS client app I receive a 404. Reverting to the previous docker image fixes this.

### Expected Behavior

Book should be downloaded.

### Steps To Reproduce

1. With a previously working server/config connect and attempt to download an epub or other ebook file

The server produces this ngnix log on the latest (broken) version

`172.17.0.1 - - [12/Aug/2023:21:26:47 -0500] "GET /fetch.php?data=53202&type=epub&id=9729&db=3 HTTP/1.1" 404 125 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/10.0 Mobile/14E277 Safari/602.1"`

And this is the log entry if I revert one release

`172.17.0.1 - - [12/Aug/2023:21:30:40 -0500] "GET /fetch.php?data=53202&type=epub&id=9729&db=3 HTTP/1.1" 200 278484 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/10.0 Mobile/14E277 Safari/602.1"`

### Environment

```markdown
- OS:Windows Server 2019 (Linux Container)
- How docker service was installed: Docker Desktop
```

### CPU architecture

x86-64

### Docker creation

```bash
docker create --name=cops -e PUID=1000 -e PGID=1000 -e TZ=EST -p 8080:80 -p 8443:443 -v b:/cops/config:/config -v b:/cops/books:/books --restart always linuxserver/cops:latest
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-20 │ 2023-06-24 │ /config/nginx/ssl.conf                                                 │
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
│ 2018-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by Chirishman** [comment] 2023-08-14 14:05
@drizuid I poked around in the commits to see what was happening here. I like the goal of switching to a maintained fork on principal but this has produced a breaking change for people using the prior release.

Do we have any documentation on migrating config files and existing libraries?

Do you know if any of the subsequent releases in the last day have fixed the 404 on download issue I have been seeing?

**Comment by drizuid** [comment] 2023-08-14 14:08
have you tried fixing the confs your logs tell you to fix yet? 
We would not have any documentation as we are not the devs, you would need to check the upstream documentation. That said, you have a conf from 2018.. i would start with what your logs tell you to do.

**Comment by Chirishman** [comment] 2023-08-14 14:42
It's not throwing any errors in any logs that I can find except for the 404 error that I included in my first post.

Browsing the library works properly in a web browser and in an OPDS client but when actually clicking the "download epub link" to download a book (with the same url for the download as shown) it produces a 404 on the updated container and doesn't 404 on the previous release.

I don't think the host is really likely to be relevant here. The container is running, is clearly able to access both the config file and the library sqlite DB which are passed through from the host OS just fine, it's only the action of serving the actual book files which is completely borked.

**Comment by drizuid** [comment] 2023-08-14 16:41
im referring to all 3 configs that our container logs are telling you to fix.

**Comment by Chirishman** [comment] 2023-08-22 15:49
OK, they're all updated and every book is still 404ing

```Bash
2023-08-22 11:48:27 [migrations] started
2023-08-22 11:48:27 [migrations] 01-nginx-site-confs-default: skipped
2023-08-22 11:48:27 [migrations] 02-default-location: skipped
2023-08-22 11:48:27 [migrations] done
2023-08-22 11:48:27 usermod: no changes
2023-08-22 11:48:27 ───────────────────────────────────────
2023-08-22 11:48:27 
2023-08-22 11:48:27       ██╗     ███████╗██╗ ██████╗ 
2023-08-22 11:48:27       ██║     ██╔════╝██║██╔═══██╗
2023-08-22 11:48:27       ██║     ███████╗██║██║   ██║
2023-08-22 11:48:27       ██║     ╚════██║██║██║   ██║
2023-08-22 11:48:27       ███████╗███████║██║╚██████╔╝
2023-08-22 11:48:27       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-08-22 11:48:27 
2023-08-22 11:48:27    Brought to you by linuxserver.io
2023-08-22 11:48:27 ───────────────────────────────────────
2023-08-22 11:48:27 
2023-08-22 11:48:27 To support LSIO projects visit:
2023-08-22 11:48:27 https://www.linuxserver.io/donate/
2023-08-22 11:48:27 
2023-08-22 11:48:27 ───────────────────────────────────────
2023-08-22 11:48:27 GID/UID
2023-08-22 11:48:27 ───────────────────────────────────────
2023-08-22 11:48:28 
2023-08-22 11:48:28 User UID:    1000
2023-08-22 11:48:28 User GID:    1000
2023-08-22 11:48:28 ───────────────────────────────────────
2023-08-22 11:48:28 
2023-08-22 11:48:28 using keys found in /config/keys
2023-08-22 11:48:34 **** The following site-confs have extensions other than .conf ****
2023-08-22 11:48:34 **** This may be due to user customization. ****
2023-08-22 11:48:34 **** You should review the files and rename them to use the .conf extension or remove them. ****
2023-08-22 11:48:34 **** nginx.conf will only include site-confs with the .conf extension. ****
2023-08-22 11:48:34 /config/nginx/site-confs/default.conf.bak
2023-08-22 11:48:34 [custom-init] No custom files found, skipping...
2023-08-22 11:48:35 [ls.io-init] done.
```

**Comment by drizuid** [comment] 2023-08-22 16:07
can test using wsl2 paths (/home/user/blah) rather than windows paths (b:\something) to remove the extra translation layer? Bear in mind that this also could be docker desktop breaking things, and that we do not support docker desktop on any OS, though to be clear, we also do not support windows.

**Comment by Chirishman** [comment] 2023-08-22 16:30
Yeah I've been running this container in this environment for >3 years now I know there can be drawbacks with that, it's one of the first things I checked because I've had it break before when updating DockerDesktop versions (at one point they broke traversal of symlinks/ntfs junctions which was a pain)

Counterpoint:

1. It is successfully accessing the `metadata.db` files to generate the actual content of the index
2. From an interactive session with the container I can `cd` into the mounted folders that the books are in and `tail metadata.opf` in a an individual book directory to successfully print the contents of a file to the console
3. If I run the below command (instead of using `linuxserver/cops:latest`) *everything* works as expected. If it was an environmental issue on the host it should be broken no matter what version of the container I use.

```PowerShell
docker stop cops
docker rm cops
docker create --name=cops -e PUID=1000 -e PGID=1000 -e TZ=EST -p 8080:80 -p 8443:443 -v b:/cops/config:/config -v b:/cops/books:/books --restart always 33c50831617848bc4ed714633a988404031971673efb68f094972dbfb28c57ae
docker start cops
```

**Comment by drizuid** [comment] 2023-08-22 18:20
I would suggest you stick with what works for you then. As a note, there are no counter points in a support request. I was trying to help you with something that is completely unsupported.

**Comment by drizuid** [comment] 2023-08-22 19:23
If you have any ideas, we are happy to push changes though, we do have users that are using supported methods and are not experiencing these issues. 

For others who may come to this thread, mikespub is the new dev/maintainer of COPS now.

**Comment by Chirishman** [comment] 2023-08-22 21:51
> Obviously when a user is unwilling to make simple changes to help troubleshoot we just.. don't care at that point :D

It's not a simple change, I'm running this on a Windows Server 2019 host and WSL is not currently installed on the host at all.

**Comment by mikespub** [comment] 2023-08-23 11:04
FYI @drizuid once the nginx config files were updated as you asked, there were no more issues with linuxserver/docker-cops or the COPS application itself.

And in this particular case, the use of windows paths didn't affect things either - but as Chirishman mentioned it wasn't on a Windows client with Docker Desktop and WSL.

The issue was with a modified file structure for books to fit some patch on the old COPS version that no longer applied...

**Comment by drizuid** [comment] 2023-10-11 13:17
@mikespub sorry for being away so long, I wanted to clarify, your implication above was that the issue is determined, but im not following if there is something I need to adjust on our side or if resolution came from your side. Please let me know if there is an action for us or if this is resolved. thanks!  
(as you may know, none of us on the team are using COPS, so support is a bit sketchy from us on it)

**Comment by mikespub** [comment] 2023-10-11 18:48
hi @drizuid no worries - no change was needed for either docker-cops or COPS itself.

In this particular case, the custom configurations of all the different pieces were ... not quite aligned anymore :-)

The config update for nginx you described above fixed the 1st step, the config update for COPS we discussed in https://github.com/mikespub-org/seblucas-cops/issues/21 fixed the 2nd step, and his own filesystem setup fixed the 3rd part.

It just took a while to figure out...

**Comment by drizuid** [comment] 2023-10-11 20:27
thanks! I'll go ahead and close this!

**Closed by drizuid** 2023-10-11 20:27 UTC
Labels: no-issue-activity
